// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "enter your DEVICE ID "; // Device Id from Arduino Device Secret Key.pdf

const char SSID[]               = "null";    // Network SSID (name)
const char PASS[]               = "null";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "enter your SECRET KEY";    // Secret Key from Arduino Device Secret Key.pdf

void onFourChange();
void onOneChange();
void onThreeChange();
void onTwoChange();
void onTempoChange();

CloudSwitch four;
CloudSwitch one;
CloudSwitch three;
CloudSwitch two;
CloudTemperatureSensor tempo;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(four, READWRITE, ON_CHANGE, onFourChange);
  ArduinoCloud.addProperty(one, READWRITE, ON_CHANGE, onOneChange);
  ArduinoCloud.addProperty(three, READWRITE, ON_CHANGE, onThreeChange);
  ArduinoCloud.addProperty(two, READWRITE, ON_CHANGE, onTwoChange);
  ArduinoCloud.addProperty(tempo, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
