// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d575b1e2-af77-44e2-a75e-0697197c7a2d";

const char SSID[]               = "null";    // Network SSID (name)
const char PASS[]               = "null";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "cAV7WmQoe@za!NvflthQvPXrX";    // Secret device password

void onFourChange();
void onOneChange();
void onThreeChange();
void onTwoChange();
void onTempoChange();

CloudSwitch four;
CloudSwitch one;
CloudSwitch three;
CloudSwitch two;
CloudTemperatureSensor tempo;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(four, READWRITE, ON_CHANGE, onFourChange);
  ArduinoCloud.addProperty(one, READWRITE, ON_CHANGE, onOneChange);
  ArduinoCloud.addProperty(three, READWRITE, ON_CHANGE, onThreeChange);
  ArduinoCloud.addProperty(two, READWRITE, ON_CHANGE, onTwoChange);
  ArduinoCloud.addProperty(tempo, READWRITE, ON_CHANGE, onTempoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
